- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    # - name: Fetch from vault
    #   uri:
    #     url: "{{ url }}"
    #     method: GET
    #     headers:
    #       X-Vault-Token: "{{ token }}"
    #   register: response
    
    # - debug:
    #     msg:
    #      - "{{response}}"

- name: Lookup secret from vault
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Lookup and Output Entire Secret from Vault
      debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/my-secret:demo' )}}"

    # - name: Vault Server
    #   ansible.builtin.debug:
    #     msg: "'{{ lookup('ansible.builtin.env', 'VAULT_ADDR') }}'"
      
    # - name: Vault Method
    #   ansible.builtin.debug:
    #     msg: "'{{ lookup('ansible.builtin.env', 'VAULT_AUTH_METHOD') }}'"

    # - name: Vault ROLE
    #   ansible.builtin.debug:
    #     msg: "'{{ lookup('ansible.builtin.env', 'VAULT_ROLE_ID') }}'"

    # - name: Vault SECRET
    #   ansible.builtin.debug:
    #     msg: "'{{ lookup('ansible.builtin.env', 'VAULT_SECRET_ID') }}'"

    # - name: Authenticate with a Vault app role
    #   debug:
    #     msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/my-secret auth_method=approle role_id={{role_id}} secret_id={{secret_id}}') }}"