- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

- name: Lookup secret from vault
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Lookup and Output Entire Secret from Vault
      debug:
        msg: "{{ lookup('vault', 'secret=kv/data/my-secret')}}"