- name: Hello World Sample
  hosts: localhost
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: Fetch from vault
      uri:
        url: "{{ url }}"
        method: GET
        headers:
          X-Vault-Token: "{{ token }}"
      register: response
    
    - debug:
        msg:
         - "{{response}}"

# - name: Lookup secret from vault
#   hosts: localhost
#   gather_facts: false
#   connection: local
#   tasks:
#     - name: Lookup and Output Entire Secret from Vault
#       debug:
#         msg: "{{ lookup('hashi_vault', 'secret=kv/data/my-secret')}}"